<?php return array (
  'emails.manualPaymentNotification.subject' => 'Manual Payment Notification',
  'emails.manualPaymentNotification.body' => 'A manual payment needs to be processed for the journal {$contextName} and the user {$userFullName} (username &quot;{$userName}&quot;).<br />
<br />
The item being paid for is &quot;{$itemName}&quot;.<br />
The cost is {$itemCost} ({$itemCurrencyCode}).<br />
<br />
This email was generated by Open Journal Systems\' Manual Payment plugin.',
  'emails.manualPaymentNotification.description' => 'This email template is used to notify a journal manager contact that a manual payment was requested.',
);